name: Locale CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "**/*.sh"
      - "**/*.bat"
      - "**/*.exe"
      - "**/*.mo"
      
jobs:
  deploy:
    runs-on: [self-hosted, knotters, translation, deploy, production]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v2
      with:
        clean: false
    - name: Compile messages
      working-directory: /home/ubuntu/knotters-runner/_work/knotters/knotters
      run: |
        /home/ubuntu/knotters/bin/python3 manage.py compilemessages
